INSERT INTO EDAP_MDC.ETL_PROJECT_STAGING_TABLE
(
    PROJECT_ID,
    DATASET_ID,
    STAGING_TABLE_NAME,
    SOURCE_SYSTEM_ID,
    DEDUP_REQUIRED,
    SELECT_DEDUP_DESC_COLUMNS,
    SELECT_DEDUP_ASC_COLUMNS
)
SELECT
    2,
    121,
    'ECDM_C_B_ADDR_OUT',
    45,
    FALSE,
    '',
    ''

INSERT INTO EDAP_MDC.ETL_PROJECT_STAGING_TABLE
(
    PROJECT_ID,
    DATASET_ID,
    STAGING_TABLE_NAME,
    SOURCE_SYSTEM_ID,
    DEDUP_REQUIRED,
    SELECT_DEDUP_DESC_COLUMNS,
    SELECT_DEDUP_ASC_COLUMNS
)
SELECT
    2,
    276,
    'ECDM_PARTY_AGMT_ADDR_OUT',
    45,
    FALSE,
    '',
    '';

INSERT INTO EDAP_MDC.ETL_PROJECT_STAGING_TABLE
(
    PROJECT_ID,
    DATASET_ID,
    STAGING_TABLE_NAME,
    SOURCE_SYSTEM_ID,
    DEDUP_REQUIRED,
    SELECT_DEDUP_DESC_COLUMNS,
    SELECT_DEDUP_ASC_COLUMNS
)
SELECT
    2,
    277,
    'ECDM_PARTY_AGMT_ADDR_OUT',
    45,
    FALSE,
    '',
    '';

INSERT INTO EDAP_MDC.ETL_PROJECT_STAGING_TABLE
(
    PROJECT_ID,
    DATASET_ID,
    STAGING_TABLE_NAME,
    SOURCE_SYSTEM_ID,
    DEDUP_REQUIRED,
    SELECT_DEDUP_DESC_COLUMNS,
    SELECT_DEDUP_ASC_COLUMNS
)
SELECT
    2,
    278,
    'ECDM_C_B_AGRMNT_OUT',
    45,
    FALSE,
    '',
    '';
