TRUNCATE TABLE EDW_WORK.ECDM_DIM_AGREEMENT;


CREATE LOCAL TEMPORARY TABLE ECDM_DIM_AGREEMENT_BENE_ID ON COMMIT PRESERVE ROWS AS
SELECT DISTINCT
    UUID_GEN(PREHASH_VALUE(
        CLEAN_STRING(SRC.CARR_ADMIN_SYS_CD),
        CLEAN_STRING('IPA'),
        CLEAN_STRING(SRC.HLDG_KEY_PFX),
        CLEAN_STRING(SRC.HLDG_KEY),
        CLEAN_STRING(SRC.HLDG_KEY_SFX)))::UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID
FROM PROD_STND_PRTY_VW_TERSUN.PRTY_AGMT_BENE_DATA_VW SRC;


INSERT INTO ECDM_DIM_AGREEMENT_BENE_ID
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID
)
SELECT DIM_AGREEMENT_NATURAL_KEY_HASH_UUID
FROM EDW_TDSUNSET.REL_PARTY_AGREEMENT SRC
WHERE SRC.REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID = UUID_GEN(PREHASH_VALUE(CLEAN_STRING('BENE')))::UUID;


INSERT INTO EDW_WORK.ECDM_DIM_AGREEMENT
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    AGREEMENT_NR_PFX,
    AGREEMENT_NR,
    AGREEMENT_NR_SFX,
    AGREEMENT_SOURCE_CDE,
    AGREEMENT_TYPE_CDE,
    AGREEMENT_STATUS_CDE,
    AGREEMENT_STATUS_REASON_CDE,
    BENEFICIARIES_RECORDED_IND,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID
)
SELECT
    UUID_GEN(PREHASH_VALUE(
        CLEAN_STRING(SRC.CARR_ADMIN_SYS_CD),
        CLEAN_STRING('IPA'),
        CLEAN_STRING(SRC.HLDG_KEY_PFX),
        CLEAN_STRING(SRC.HLDG_KEY),
        CLEAN_STRING(SRC.HLDG_KEY_SFX)))::UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    CLEAN_STRING(SRC.HLDG_KEY_PFX) AS AGREEMENT_NR_PFX,
    CLEAN_STRING(SRC.HLDG_KEY) AS AGREEMENT_NR,
    CLEAN_STRING(SRC.HLDG_KEY_SFX) AS AGREEMENT_NR_SFX,
    CLEAN_STRING(SRC.CARR_ADMIN_SYS_CD) AS AGREEMENT_SOURCE_CDE,
    CLEAN_STRING('IPA') AS AGREEMENT_TYPE_CDE,
    CLEAN_STRING(SRC.AGMT_STUS_CD) AS AGREEMENT_STATUS_CDE,
    CLEAN_STRING(SRC.AGMT_STUS_RSN_CD) AS AGREEMENT_STATUS_REASON_CDE,
    TRUE AS BENEFICIARIES_RECORDED_IND,
    SRC.AGMT_FR_DT AS BEGIN_DT,
    SRC.AGMT_FR_DT AS BEGIN_DTM,
    CURRENT_TIMESTAMP(6) AS ROW_PROCESS_DTM,
    0 AS AUDIT_ID,
    CASE WHEN SRC.SRC_DEL_IND = 'Y' THEN TRUE ELSE FALSE END AS LOGICAL_DELETE_IND,
    UUID_GEN(PREHASH_VALUE(
        CLEAN_STRING(SRC.HLDG_KEY_PFX),
        CLEAN_STRING(SRC.HLDG_KEY),
        CLEAN_STRING(SRC.HLDG_KEY_SFX),
        CLEAN_STRING(SRC.CARR_ADMIN_SYS_CD),
        CLEAN_STRING(SRC.AGMT_STUS_CD),
        CLEAN_STRING(SRC.AGMT_STUS_RSN_CD)
    ))::UUID AS CHECK_SUM,
    CASE WHEN SRC.CURR_IND = 'Y' THEN TRUE ELSE FALSE END AS CURRENT_ROW_IND,
    SRC.AGMT_TO_DT AS END_DT,
    SRC.AGMT_TO_DT END_DTM,
    SRC.SRC_SYS_ID AS SOURCE_SYSTEM_ID,
    FALSE AS RESTRICTED_ROW_IND,
    0 AS UPDATE_AUDIT_ID

FROM PROD_STND_PRTY_VW_TERSUN.AGMT_VW SRC
WHERE UUID_GEN(PREHASH_VALUE(
    CLEAN_STRING(SRC.CARR_ADMIN_SYS_CD),
    CLEAN_STRING('IPA'),
    CLEAN_STRING(SRC.HLDG_KEY_PFX),
    CLEAN_STRING(SRC.HLDG_KEY),
    CLEAN_STRING(SRC.HLDG_KEY_SFX)))::UUID IN
        (SELECT DISTINCT DIM_AGREEMENT_NATURAL_KEY_HASH_UUID FROM ECDM_DIM_AGREEMENT_BENE_ID);


INSERT INTO EDW_WORK.ECDM_DIM_AGREEMENT
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    AGREEMENT_NR_PFX,
    AGREEMENT_NR,
    AGREEMENT_NR_SFX,
    AGREEMENT_SOURCE_CDE,
    AGREEMENT_TYPE_CDE,
    AGREEMENT_STATUS_CDE,
    AGREEMENT_STATUS_REASON_CDE,
    BENEFICIARIES_RECORDED_IND,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID
)
SELECT
    UUID_GEN(PREHASH_VALUE(
        CLEAN_STRING(SRC.CARR_ADMIN_SYS_CD),
        CLEAN_STRING('IPA'),
        CLEAN_STRING(SRC.HLDG_KEY_PFX),
        CLEAN_STRING(SRC.HLDG_KEY),
        CLEAN_STRING(SRC.HLDG_KEY_SFX)))::UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    CLEAN_STRING(SRC.HLDG_KEY_PFX) AS AGREEMENT_NR_PFX,
    CLEAN_STRING(SRC.HLDG_KEY) AS AGREEMENT_NR,
    CLEAN_STRING(SRC.HLDG_KEY_SFX) AS AGqREEMENT_NR_SFX,
    CLEAN_STRING(SRC.CARR_ADMIN_SYS_CD) AS AGREEMENT_SOURCE_CDE,
    CLEAN_STRING('IPA') AS AGREEMENT_TYPE_CDE,
    CLEAN_STRING(SRC.AGMT_STUS_CD) AS AGREEMENT_STATUS_CDE,
    CLEAN_STRING(SRC.AGMT_STUS_RSN_CD) AS AGREEMENT_STATUS_REASON_CDE,
    FALSE AS BENEFICIARIES_RECORDED_IND,
    SRC.AGMT_FR_DT AS BEGIN_DT,
    SRC.AGMT_FR_DT AS BEGIN_DTM,
    CURRENT_TIMESTAMP(6) AS ROW_PROCESS_DTM,
    0 AS AUDIT_ID,
    CASE WHEN SRC.SRC_DEL_IND = 'Y' THEN TRUE ELSE FALSE END AS LOGICAL_DELETE_IND,
    UUID_GEN(PREHASH_VALUE(
        CLEAN_STRING(SRC.HLDG_KEY_PFX),
        CLEAN_STRING(SRC.HLDG_KEY),
        CLEAN_STRING(SRC.HLDG_KEY_SFX),
        CLEAN_STRING(SRC.CARR_ADMIN_SYS_CD),
        CLEAN_STRING(SRC.AGMT_STUS_CD),
        CLEAN_STRING(SRC.AGMT_STUS_RSN_CD)
    ))::UUID AS CHECK_SUM,
    CASE WHEN SRC.CURR_IND = 'Y' THEN TRUE ELSE FALSE END AS CURRENT_ROW_IND,
    SRC.AGMT_TO_DT AS END_DT,
    SRC.AGMT_TO_DT END_DTM,
    SRC.SRC_SYS_ID AS SOURCE_SYSTEM_ID,
    FALSE AS RESTRICTED_ROW_IND,
    0 AS UPDATE_AUDIT_ID

FROM PROD_STND_PRTY_VW_TERSUN.AGMT_VW SRC
WHERE UUID_GEN(PREHASH_VALUE(
    CLEAN_STRING(SRC.CARR_ADMIN_SYS_CD),
    CLEAN_STRING('IPA'),
    CLEAN_STRING(SRC.HLDG_KEY_PFX),
    CLEAN_STRING(SRC.HLDG_KEY),
    CLEAN_STRING(SRC.HLDG_KEY_SFX)))::UUID NOT IN
        (SELECT DISTINCT DIM_AGREEMENT_NATURAL_KEY_HASH_UUID FROM ECDM_DIM_AGREEMENT_BENE_ID);


DELETE FROM EDW_TDSUNSET.DIM_AGREEMENT WHERE SOURCE_SYSTEM_ID IN ('44', '45');


INSERT INTO EDW_TDSUNSET.DIM_AGREEMENT
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    AGREEMENT_NR_PFX,
    AGREEMENT_NR,
    AGREEMENT_NR_SFX,
    AGREEMENT_SOURCE_CDE,
    AGREEMENT_TYPE_CDE,
    MASTER_CONTRACT_GROUP_ID,
    SPONSOR_ID,
    PLAN_ID,
    SUBSCRIBER_ID,
    PARTICIPANT_ID,
    ICU_ID,
    MASTER_CONTRACT_GROUP_NM_NATIONAL_DESC,
    PLAN_NM_1_TXT,
    PLAN_NM_2_TXT,
    PLAN_NM_3_TXT,
    SUBSCRIBER_NR,
    AGREEMENT_STATUS_CDE,
    AGREEMENT_STATUS_REASON_CDE,
    ALLOW_ROLLOVER_IND,
    APPLICATION_SUBMIT_DT,
    BENEFICIARIES_RECORDED_IND,
    CONVERSION_EXPIRED_IND,
    CONVERSION_ELIGIBILITY_START_DT,
    CONVERSION_ELIGIBILITY_END_DT,
    DEFAULT_VOLUNTARY_DEFERRAL_RT,
    ENROLLMENT_DT,
    ENROLLMENT_ELIGIBILITY_DT,
    ENROLLMENT_START_DT,
    ENROLLMENT_END_DT,
    ENROLLMENT_STATUS_CDE,
    ENROLLMENT_TYPE_CDE,
    FACE_AMT,
    INTERNAL_PLAN_ID,
    ISSUE_DT,
    PARTICIPATION_DT,
    SOLICITATION_DT,
    SOLICITATION_IND,
    TAFT_HARTLY_IND,
    ELECTRONIC_CONTRIBUTION_CHANGE_IND,
    PRE_TAX_AUTO_INCREASE_CONTRIBUTION_RT,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    NEXT_PAYMENT_DT,
    NEXT_PAYMENT_AMT,
    CURRENT_PRINCIPAL_AMT,
    LOAN_BOOKED_COUPON_RT,
    LOAN_BOOKED_AMT,
    LOAN_REQUESTED_COUPON_RT,
    LOAN_REQUESTED_AMT,
    LOAN_MONTHS_TO_MATURITY_VAL,
    LOAN_DEGREE_PROGRAM_DESC,
    DECISIONING_ANNUAL_INCOME_AMT,
    APPLICATION_STATUS_DT,
    LOAN_REPORT_UNIQUE_HASH_ID,
    ESERVICE_IND,
    AGREEMENT_EFFECTIVE_DT,
    UPDATE_AUDIT_ID,
    TERMINATED_PARTICIPANT_SERVICING_IND,
    MANAGED_ACCOUNTS_ELIGIBILITY_IND,
    MANAGED_ACCOUNTS_PARTICIPATION_IND
)
SELECT
    SRC.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    SRC.AGREEMENT_NR_PFX,
    SRC.AGREEMENT_NR,
    SRC.AGREEMENT_NR_SFX,
    SRC.AGREEMENT_SOURCE_CDE,
    SRC.AGREEMENT_TYPE_CDE,
    SRC.MASTER_CONTRACT_GROUP_ID,
    SRC.SPONSOR_ID,
    SRC.PLAN_ID,
    SRC.SUBSCRIBER_ID,
    SRC.PARTICIPANT_ID,
    SRC.ICU_ID,
    SRC.MASTER_CONTRACT_GROUP_NM_NATIONAL_DESC,
    SRC.PLAN_NM_1_TXT,
    SRC.PLAN_NM_2_TXT,
    SRC.PLAN_NM_3_TXT,
    SRC.SUBSCRIBER_NR,
    SRC.AGREEMENT_STATUS_CDE,
    SRC.AGREEMENT_STATUS_REASON_CDE,
    SRC.ALLOW_ROLLOVER_IND,
    SRC.APPLICATION_SUBMIT_DT,
    SRC.BENEFICIARIES_RECORDED_IND,
    SRC.CONVERSION_EXPIRED_IND,
    SRC.CONVERSION_ELIGIBILITY_START_DT,
    SRC.CONVERSION_ELIGIBILITY_END_DT,
    SRC.DEFAULT_VOLUNTARY_DEFERRAL_RT,
    SRC.ENROLLMENT_DT,
    SRC.ENROLLMENT_ELIGIBILITY_DT,
    SRC.ENROLLMENT_START_DT,
    SRC.ENROLLMENT_END_DT,
    SRC.ENROLLMENT_STATUS_CDE,
    SRC.ENROLLMENT_TYPE_CDE,
    SRC.FACE_AMT,
    SRC.INTERNAL_PLAN_ID,
    SRC.ISSUE_DT,
    SRC.PARTICIPATION_DT,
    SRC.SOLICITATION_DT,
    SRC.SOLICITATION_IND,
    SRC.TAFT_HARTLY_IND,
    SRC.ELECTRONIC_CONTRIBUTION_CHANGE_IND,
    SRC.PRE_TAX_AUTO_INCREASE_CONTRIBUTION_RT,
    SRC.BEGIN_DT,
    SRC.BEGIN_DTM,
    SRC.ROW_PROCESS_DTM,
    SRC.AUDIT_ID,
    SRC.LOGICAL_DELETE_IND,
    SRC.CHECK_SUM,
    SRC.CURRENT_ROW_IND,
    SRC.END_DT,
    SRC.END_DTM,
    SRC.SOURCE_SYSTEM_ID,
    SRC.RESTRICTED_ROW_IND,
    SRC.NEXT_PAYMENT_DT,
    SRC.NEXT_PAYMENT_AMT,
    SRC.CURRENT_PRINCIPAL_AMT,
    SRC.LOAN_BOOKED_COUPON_RT,
    SRC.LOAN_BOOKED_AMT,
    SRC.LOAN_REQUESTED_COUPON_RT,
    SRC.LOAN_REQUESTED_AMT,
    SRC.LOAN_MONTHS_TO_MATURITY_VAL,
    SRC.LOAN_DEGREE_PROGRAM_DESC,
    SRC.DECISIONING_ANNUAL_INCOME_AMT,
    SRC.APPLICATION_STATUS_DT,
    SRC.LOAN_REPORT_UNIQUE_HASH_ID,
    SRC.ESERVICE_IND,
    SRC.AGREEMENT_EFFECTIVE_DT,
    SRC.UPDATE_AUDIT_ID,
    SRC.TERMINATED_PARTICIPANT_SERVICING_IND,
    SRC.MANAGED_ACCOUNTS_ELIGIBILITY_IND,
    SRC.MANAGED_ACCOUNTS_PARTICIPATION_IND

FROM EDW_WORK.ECDM_DIM_AGREEMENT SRC WHERE SRC.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID NOT IN
    (SELECT DISTINCT DIM_AGREEMENT_NATURAL_KEY_HASH_UUID FROM EDW_TDSUNSET.DIM_AGREEMENT);
