TRUNCATE TABLE EDW_STAGING.ECDM_PRTY_AGMT_ADDR_OUT_SNAPSHOT;


INSERT INTO EDW_STAGING.ECDM_PRTY_AGMT_ADDR_OUT_SNAPSHOT
(
    BATCH_NR,
    ADD_UPD_DEL_IND,
    MEMBER_ID,
    CARR_ADMN_SYS_CD,
    HLDG_KEY_PFX,
    AGRMNT_NUM,
    HLDG_KEY_SFX,
    ROLE_TP,
    SUB_ROLE_TP,
    ADDR_TP,
    ADDR_HASH_KEY,
    REL_START_DATE,
    REL_END_DATE,
    ATTN_LINE,
    HUB_STATE_IND,
    LST_UPDT_OPER_CD,
    SRC_LST_MOD_TS,
    ECDM_END_TS,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    SOURCE_SYSTEM_ID,
    CURRENT_BATCH
)
SELECT
    0 AS BATCH_NR,
    'I'AS ADD_UPD_DEL_IND,
    SRC.SRC_SYS_PRTY_ID AS MEMBER_ID,
    SRC.CARR_ADMIN_SYS_CD AS CARR_ADMN_SYS_CD,
    SRC.HLDG_KEY_PFX AS HLDG_KEY_PFX,
    SRC.HLDG_KEY AS AGRMNT_NUM,
    SRC.HLDG_KEY_SFX AS HLDG_KEY_SFX,
    SRC.PRTY_AGMT_RLE_CD AS ROLE_TP,
    SRC.PRTY_AGMT_RLE_STYP_CD AS SUB_ROLE_TP,
    SRC.AD_TYP_CD AS ADDR_TP,
    SRC.SRC_SYS_AD_ID AS ADDR_HASH_KEY,
    NULL AS REL_START_DATE,
    NULL AS REL_END_DATE,
    SRC.ATTN_LINE AS ATTN_LINE,
    CASE WHEN SRC_DEL_IND = 'Y' THEN -1 ELSE 1 END AS HUB_STATE_IND,
    NULL AS LST_UPDT_OPER_CD,
    NULL AS SRC_LST_MOD_TS,
    NULL AS ECDM_END_TS,
    NULL AS ROW_PROCESS_DTM,
    NULL AS AUDIT_ID,
    SRC.SRC_SYS_ID AS SOURCE_SYSTEM_ID,
    TRUE AS CURRENT_BATCH
FROM PROD_STND_PRTY_VW_TERSUN.PRTY_AGMT_AD_VW SRC;
