TRUNCATE TABLE EDW_WORK.ECDM_DIM_ADDRESS;


TRUNCATE TABLE EDW_STAGING.ECDM_DIM_ADDRESS_PRE_WORK;


-- First we aggreate all data into prework table
INSERT INTO EDW_STAGING.ECDM_DIM_ADDRESS_PRE_WORK
(
    DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    ATTENTION_LINE_TXT,
    ADDRESS_STREET_1_TXT,
    ADDRESS_STREET_2_TXT,
    ADDRESS_STREET_3_TXT,
    ADDRESS_STREET_4_TXT,
    CITY_NM,
    STATE_CDE,
    ZIP_CDE,
    ZIP_6_9_CDE,
    ZIP_10_13_CDE,
    COUNTRY_CDE,
    ADDRESS_VALIDATION_CDE,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    FOREIGN_POSTAL_CDE,
    FULL_POSTAL_CDE,
    ADDRESS_VERIFIED_DT,
    SOURCE_SYSTEM_ADDRESS_ID,
    OPERATOR_IND

)
SELECT
    UUID_GEN(PREHASH_VALUE(
        SRC.ADDRESS_STREET_1_TXT,
        SRC.ADDRESS_STREET_2_TXT,
        SRC.ADDRESS_STREET_3_TXT,
        SRC.ADDRESS_STREET_4_TXT,
        SRC.CITY_NM,
        SRC.STATE_CDE,
        SRC.ZIP_CDE,
        SRC.ZIP_6_9_CDE,
        SRC.ZIP_10_13_CDE,
        SRC.COUNTRY_CDE))::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    SRC.ATTENTION_LINE_TXT AS ATTENTION_LINE_TXT,
    SRC.ADDRESS_STREET_1_TXT AS ADDRESS_STREET_1_TXT,
    SRC.ADDRESS_STREET_2_TXT AS ADDRESS_STREET_2_TXT,
    SRC.ADDRESS_STREET_3_TXT AS ADDRESS_STREET_3_TXT,
    SRC.ADDRESS_STREET_4_TXT AS ADDRESS_STREET_4_TXT,
    SRC.CITY_NM AS CITY_NM,
    SRC.STATE_CDE AS STATE_CDE,
    SRC.ZIP_CDE AS ZIP_CDE,
    SRC.ZIP_6_9_CDE AS ZIP_6_9_CDE,
    SRC.ZIP_10_13_CDE AS ZIP_10_13_CDE,
    SRC.COUNTRY_CDE AS COUNTRY_CDE,
    SRC.ADDRESS_VALIDATION_CDE AS ADDRESS_VALIDATION_CDE,
    SRC.SRC_LST_MOD_TS::DATE AS BEGIN_DT,
    SRC.SRC_LST_MOD_TS::TIMESTAMP AS BEGIN_DTM,
    CURRENT_TIMESTAMP(6) AS ROW_PROCESS_DTM,
    :audit_id AS AUDIT_ID,
    FALSE AS LOGICAL_DELETE_IND,
    UUID_GEN(PREHASH_VALUE(
        SRC.ADDRESS_VALIDATION_CDE,
        SRC.FOREIGN_POSTAL_CDE,
        SRC.ADDRESS_VERIFIED_DT
    ))::UUID  AS CHECK_SUM,
    TRUE CURRENT_ROW_IND,
    '9999-12-31' AS END_DT,
    '9999-12-31'::TIMESTAMP AS END_DTM,
    '45' AS SOURCE_SYSTEM_ID,
    FALSE AS RESTRICTED_ROW_IND,
    :audit_id AS UPDATE_AUDIT_ID,
    SRC.FOREIGN_POSTAL_CDE AS FOREIGN_POSTAL_CDE,
    SRC.FULL_POSTAL_CDE AS FULL_POSTAL_CDE,
    SRC.ADDRESS_VERIFIED_DT AS ADDRESS_VERIFIED_DT,
    SRC.SOURCE_SYSTEM_ADDRESS_ID AS SOURCE_SYSTEM_ADDRESS_ID,
    SRC.OPERATOR_IND AS OPERATOR_IND

FROM  (
    SELECT
        SRC_DUP.BATCH_NR AS BATCH_NR,
        NULL AS ATTENTION_LINE_TXT,
        CLEAN_STRING(SRC_DUP.ADDR_LINE_1) AS ADDRESS_STREET_1_TXT,
        CLEAN_STRING(SRC_DUP.ADDR_LINE_2) AS ADDRESS_STREET_2_TXT,
        CLEAN_STRING(SRC_DUP.ADDR_LINE_3) AS ADDRESS_STREET_3_TXT,
        CLEAN_STRING(SRC_DUP.ADDR_LINE_4) AS ADDRESS_STREET_4_TXT,
        CLEAN_STRING(SRC_DUP.CITY) AS CITY_NM,
        CLEAN_STRING(SRC_DUP.STATE) AS STATE_CDE,
        CLEAN_STRING(SRC_DUP.POSTAL_CD) AS ZIP_CDE,
        CLEAN_STRING(SRC_DUP.POSTAL_EXT_CD) AS ZIP_6_9_CDE,
        CLEAN_STRING(SRC_DUP.ZIP_10_13_NR) AS ZIP_10_13_CDE,
        CLEAN_STRING(SRC_DUP.COUNTRY_CD) AS COUNTRY_CDE,
        CLEAN_STRING(SRC_DUP.VALIDATION_MSG) AS ADDRESS_VALIDATION_CDE,
        SRC_DUP.AD_VER_DT AS ADDRESS_VERIFIED_DT,
        CASE WHEN CLEAN_STRING(SRC_DUP.DMST_FRGN_CD) = CLEAN_STRING('FOR')
            THEN CLEAN_STRING(SRC_DUP.POSTAL_CD) ELSE NULL END AS FOREIGN_POSTAL_CDE,
        CLEAN_STRING(SRC_DUP.ADDR_HASH_KEY) AS SOURCE_SYSTEM_ADDRESS_ID,
        CLEAN_STRING(SRC_DUP.ZIP_CD) AS FULL_POSTAL_CDE,
        SRC_DUP.ADD_UPD_DEL_IND AS OPERATOR_IND,
        SRC_DUP.SRC_LST_MOD_TS AS SRC_LST_MOD_TS,
        ROW_NUMBER() OVER (PARTITION BY
            CLEAN_STRING(SRC_DUP.ADDR_LINE_1),
            CLEAN_STRING(SRC_DUP.ADDR_LINE_2),
            CLEAN_STRING(SRC_DUP.ADDR_LINE_3),
            CLEAN_STRING(SRC_DUP.ADDR_LINE_4),
            CLEAN_STRING(SRC_DUP.CITY),
            CLEAN_STRING(SRC_DUP.STATE),
            CLEAN_STRING(SRC_DUP.POSTAL_CD),
            CLEAN_STRING(SRC_DUP.POSTAL_EXT_CD),
            CLEAN_STRING(SRC_DUP.ZIP_10_13_NR),
            CLEAN_STRING(SRC_DUP.COUNTRY_CD) ORDER BY SRC_DUP.SRC_LST_MOD_TS, SRC_DUP.ADDR_HASH_KEY DESC) AS RNK

    FROM EDW_STAGING.ECDM_C_B_ADDR_OUT SRC_DUP
) SRC
WHERE SRC.RNK = 1;


-- New delete logic
INSERT INTO EDW_WORK.ECDM_DIM_ADDRESS
(
    DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    ATTENTION_LINE_TXT,
    ADDRESS_STREET_1_TXT,
    ADDRESS_STREET_2_TXT,
    ADDRESS_STREET_3_TXT,
    ADDRESS_STREET_4_TXT,
    CITY_NM,
    STATE_CDE,
    ZIP_CDE,
    ZIP_6_9_CDE,
    ZIP_10_13_CDE,
    COUNTRY_CDE,
    ADDRESS_VALIDATION_CDE,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    FOREIGN_POSTAL_CDE,
    FULL_POSTAL_CDE,
    ADDRESS_VERIFIED_DT,
    SOURCE_SYSTEM_ADDRESS_ID
)
SELECT
    SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    SRC.ATTENTION_LINE_TXT AS ATTENTION_LINE_TXT,
    SRC.ADDRESS_STREET_1_TXT AS ADDRESS_STREET_1_TXT,
    SRC.ADDRESS_STREET_2_TXT AS ADDRESS_STREET_2_TXT,
    SRC.ADDRESS_STREET_3_TXT AS ADDRESS_STREET_3_TXT,
    SRC.ADDRESS_STREET_4_TXT AS ADDRESS_STREET_4_TXT,
    SRC.CITY_NM AS CITY_NM,
    SRC.STATE_CDE AS STATE_CDE,
    SRC.ZIP_CDE AS ZIP_CDE,
    SRC.ZIP_6_9_CDE AS ZIP_6_9_CDE,
    SRC.ZIP_10_13_CDE AS ZIP_10_13_CDE,
    SRC.COUNTRY_CDE AS COUNTRY_CDE,
    SRC.ADDRESS_VALIDATION_CDE AS ADDRESS_VALIDATION_CDE,
    CASE WHEN TGT.BEGIN_DT IS NULL THEN '0001-01-01' ELSE TGT.BEGIN_DT END AS BEGIN_DT,
    CASE WHEN TGT.BEGIN_DTM IS NULL THEN '0001-01-01' ELSE TGT.BEGIN_DTM END AS BEGIN_DTM,
    CURRENT_TIMESTAMP(6) AS ROW_PROCESS_DTM,
    :audit_id AS AUDIT_ID,
    FALSE AS LOGICAL_DELETE_IND,
    SRC.CHECK_SUM AS CHECK_SUM,
    FALSE AS CURRENT_ROW_IND,
    SRC.BEGIN_DT AS END_DT,
    SRC.BEGIN_DTM AS END_DTM,
    '45' AS SOURCE_SYSTEM_ID,
    FALSE AS RESTRICTED_ROW_IND,
    :audit_id AS UPDATE_AUDIT_ID,
    SRC.FOREIGN_POSTAL_CDE AS FOREIGN_POSTAL_CDE,
    SRC.FULL_POSTAL_CDE AS FULL_POSTAL_CDE,
    SRC.ADDRESS_VERIFIED_DT AS ADDRESS_VERIFIED_DT,
    SRC.SOURCE_SYSTEM_ADDRESS_ID AS SOURCE_SYSTEM_ADDRESS_ID

FROM EDW_STAGING.ECDM_DIM_ADDRESS_PRE_WORK SRC

LEFT JOIN EDW_TDSUNSET.DIM_ADDRESS TGT
ON SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID = TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID AND TGT.CURRENT_ROW_IND = TRUE
WHERE SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID NOT IN
    (SELECT UUID_GEN(PREHASH_VALUE(
        CLEAN_STRING(SNAPSHOT.ADDR_LINE_1),
        CLEAN_STRING(SNAPSHOT.ADDR_LINE_2),
        CLEAN_STRING(SNAPSHOT.ADDR_LINE_3),
        CLEAN_STRING(SNAPSHOT.ADDR_LINE_4),
        CLEAN_STRING(SNAPSHOT.CITY),
        CLEAN_STRING(SNAPSHOT.STATE),
        CLEAN_STRING(SNAPSHOT.POSTAL_CD),
        CLEAN_STRING(SNAPSHOT.POSTAL_EXT_CD),
        CLEAN_STRING(SNAPSHOT.ZIP_10_13_NR),
        CLEAN_STRING(SNAPSHOT.COUNTRY_CD)))::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID
        FROM EDW_STAGING.ECDM_C_B_ADDR_OUT_SNAPSHOT SNAPSHOT WHERE SNAPSHOT.ADD_UPD_DEL_IND != 'D')
AND SRC.OPERATOR_IND = 'D';


-- Apply insert part for all records
INSERT INTO EDW_WORK.ECDM_DIM_ADDRESS
(
    DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    ATTENTION_LINE_TXT,
    ADDRESS_STREET_1_TXT,
    ADDRESS_STREET_2_TXT,
    ADDRESS_STREET_3_TXT,
    ADDRESS_STREET_4_TXT,
    CITY_NM,
    STATE_CDE,
    ZIP_CDE,
    ZIP_6_9_CDE,
    ZIP_10_13_CDE,
    COUNTRY_CDE,
    ADDRESS_VALIDATION_CDE,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    FOREIGN_POSTAL_CDE,
    FULL_POSTAL_CDE,
    ADDRESS_VERIFIED_DT,
    SOURCE_SYSTEM_ADDRESS_ID
)
SELECT
    SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    SRC.ATTENTION_LINE_TXT AS ATTENTION_LINE_TXT,
    SRC.ADDRESS_STREET_1_TXT AS ADDRESS_STREET_1_TXT,
    SRC.ADDRESS_STREET_2_TXT AS ADDRESS_STREET_2_TXT,
    SRC.ADDRESS_STREET_3_TXT AS ADDRESS_STREET_3_TXT,
    SRC.ADDRESS_STREET_4_TXT AS ADDRESS_STREET_4_TXT,
    SRC.CITY_NM AS CITY_NM,
    SRC.STATE_CDE AS STATE_CDE,
    SRC.ZIP_CDE AS ZIP_CDE,
    SRC.ZIP_6_9_CDE AS ZIP_6_9_CDE,
    SRC.ZIP_10_13_CDE AS ZIP_10_13_CDE,
    SRC.COUNTRY_CDE AS COUNTRY_CDE,
    SRC.ADDRESS_VALIDATION_CDE AS ADDRESS_VALIDATION_CDE,
    '0001-01-01' AS BEGIN_DT,
    '0001-01-01 00:00:00' AS BEGIN_DTM,
    CURRENT_TIMESTAMP(6) AS ROW_PROCESS_DTM,
    :audit_id AS AUDIT_ID,
    FALSE AS LOGICAL_DELETE_IND,
    SRC.CHECK_SUM AS CHECK_SUM,
    TRUE AS CURRENT_ROW_IND,
    SRC.END_DT AS END_DT,
    SRC.END_DTM AS END_DTM,
    '45' AS SOURCE_SYSTEM_ID,
    FALSE AS RESTRICTED_ROW_IND,
    :audit_id AS UPDATE_AUDIT_ID,
    SRC.FOREIGN_POSTAL_CDE AS FOREIGN_POSTAL_CDE,
    SRC.FULL_POSTAL_CDE AS FULL_POSTAL_CDE,
    SRC.ADDRESS_VERIFIED_DT AS ADDRESS_VERIFIED_DT,
    SRC.SOURCE_SYSTEM_ADDRESS_ID AS SOURCE_SYSTEM_ADDRESS_ID

FROM EDW_STAGING.ECDM_DIM_ADDRESS_PRE_WORK SRC WHERE
    SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID
        NOT IN (SELECT DISTINCT DIM_ADDRESS_NATURAL_KEY_HASH_UUID FROM EDW_TDSUNSET.DIM_ADDRESS WHERE LOGICAL_DELETE_IND = FALSE)
    AND SRC.OPERATOR_IND != 'D';


-- For update we need to have two records, one for prev another for curr
-- Curr
INSERT INTO EDW_WORK.ECDM_DIM_ADDRESS
(
    DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    ATTENTION_LINE_TXT,
    ADDRESS_STREET_1_TXT,
    ADDRESS_STREET_2_TXT,
    ADDRESS_STREET_3_TXT,
    ADDRESS_STREET_4_TXT,
    CITY_NM,
    STATE_CDE,
    ZIP_CDE,
    ZIP_6_9_CDE,
    ZIP_10_13_CDE,
    COUNTRY_CDE,
    ADDRESS_VALIDATION_CDE,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    FOREIGN_POSTAL_CDE,
    FULL_POSTAL_CDE,
    ADDRESS_VERIFIED_DT,
    SOURCE_SYSTEM_ADDRESS_ID
)
SELECT
    SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    SRC.ATTENTION_LINE_TXT AS ATTENTION_LINE_TXT,
    SRC.ADDRESS_STREET_1_TXT AS ADDRESS_STREET_1_TXT,
    SRC.ADDRESS_STREET_2_TXT AS ADDRESS_STREET_2_TXT,
    SRC.ADDRESS_STREET_3_TXT AS ADDRESS_STREET_3_TXT,
    SRC.ADDRESS_STREET_4_TXT AS ADDRESS_STREET_4_TXT,
    SRC.CITY_NM AS CITY_NM,
    SRC.STATE_CDE AS STATE_CDE,
    SRC.ZIP_CDE AS ZIP_CDE,
    SRC.ZIP_6_9_CDE AS ZIP_6_9_CDE,
    SRC.ZIP_10_13_CDE AS ZIP_10_13_CDE,
    SRC.COUNTRY_CDE AS COUNTRY_CDE,
    SRC.ADDRESS_VALIDATION_CDE AS ADDRESS_VALIDATION_CDE,
    SRC.BEGIN_DT AS BEGIN_DT,
    SRC.BEGIN_DTM AS BEGIN_DTM,
    CURRENT_TIMESTAMP(6) AS ROW_PROCESS_DTM,
    :audit_id AS AUDIT_ID,
    FALSE AS LOGICAL_DELETE_IND,
    SRC.CHECK_SUM AS CHECK_SUM,
    TRUE AS CURRENT_ROW_IND,
    SRC.END_DT AS END_DT,
    SRC.END_DTM AS END_DTM,
    '45' AS SOURCE_SYSTEM_ID,
    FALSE AS RESTRICTED_ROW_IND,
    :audit_id AS UPDATE_AUDIT_ID,
    SRC.FOREIGN_POSTAL_CDE AS FOREIGN_POSTAL_CDE,
    SRC.FULL_POSTAL_CDE AS FULL_POSTAL_CDE,
    SRC.ADDRESS_VERIFIED_DT AS ADDRESS_VERIFIED_DT,
    SRC.SOURCE_SYSTEM_ADDRESS_ID AS SOURCE_SYSTEM_ADDRESS_ID

FROM EDW_STAGING.ECDM_DIM_ADDRESS_PRE_WORK SRC

WHERE
    SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID
         IN (SELECT DISTINCT DIM_ADDRESS_NATURAL_KEY_HASH_UUID FROM EDW_TDSUNSET.DIM_ADDRESS WHERE LOGICAL_DELETE_IND = FALSE)
    AND SRC.OPERATOR_IND != 'D';


-- Prev
INSERT INTO EDW_WORK.ECDM_DIM_ADDRESS
(
    DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    ATTENTION_LINE_TXT,
    ADDRESS_STREET_1_TXT,
    ADDRESS_STREET_2_TXT,
    ADDRESS_STREET_3_TXT,
    ADDRESS_STREET_4_TXT,
    CITY_NM,
    STATE_CDE,
    ZIP_CDE,
    ZIP_6_9_CDE,
    ZIP_10_13_CDE,
    COUNTRY_CDE,
    ADDRESS_VALIDATION_CDE,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    FOREIGN_POSTAL_CDE,
    FULL_POSTAL_CDE,
    ADDRESS_VERIFIED_DT,
    SOURCE_SYSTEM_ADDRESS_ID
)
SELECT
    TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    TGT.ATTENTION_LINE_TXT AS ATTENTION_LINE_TXT,
    TGT.ADDRESS_STREET_1_TXT AS ADDRESS_STREET_1_TXT,
    TGT.ADDRESS_STREET_2_TXT AS ADDRESS_STREET_2_TXT,
    TGT.ADDRESS_STREET_3_TXT AS ADDRESS_STREET_3_TXT,
    TGT.ADDRESS_STREET_4_TXT AS ADDRESS_STREET_4_TXT,
    TGT.CITY_NM AS CITY_NM,
    TGT.STATE_CDE AS STATE_CDE,
    TGT.ZIP_CDE AS ZIP_CDE,
    TGT.ZIP_6_9_CDE AS ZIP_6_9_CDE,
    TGT.ZIP_10_13_CDE AS ZIP_10_13_CDE,
    TGT.COUNTRY_CDE AS COUNTRY_CDE,
    TGT.ADDRESS_VALIDATION_CDE AS ADDRESS_VALIDATION_CDE,
    TGT.BEGIN_DT AS BEGIN_DT,
    TGT.BEGIN_DTM AS BEGIN_DTM,
    CURRENT_TIMESTAMP(6) AS ROW_PROCESS_DTM,
    TGT.AUDIT_ID AS AUDIT_ID,
    FALSE AS LOGICAL_DELETE_IND,
    TGT.CHECK_SUM AS CHECK_SUM,
    FALSE AS CURRENT_ROW_IND,
    SRC.BEGIN_DT - INTERVAL '1 day' AS END_DT,
    SRC.BEGIN_DTM - INTERVAL '1 second' AS END_DTM,
    TGT.SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID,
    TGT.RESTRICTED_ROW_IND AS RESTRICTED_ROW_IND,
    :audit_id AS UPDATE_AUDIT_ID,
    TGT.FOREIGN_POSTAL_CDE AS FOREIGN_POSTAL_CDE,
    TGT.FULL_POSTAL_CDE AS FULL_POSTAL_CDE,
    TGT.ADDRESS_VERIFIED_DT AS ADDRESS_VERIFIED_DT,
    TGT.SOURCE_SYSTEM_ADDRESS_ID AS SOURCE_SYSTEM_ADDRESS_ID

FROM EDW_STAGING.ECDM_DIM_ADDRESS_PRE_WORK SRC
LEFT JOIN EDW_TDSUNSET.DIM_ADDRESS TGT
ON SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID = TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID
AND TGT.CURRENT_ROW_IND = TRUE
WHERE
    TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID IS NOT NULL
    AND SRC.OPERATOR_IND != 'D';
