TRUNCATE TABLE EDW_WORK.ECDM_DIM_AGREEMENT;


TRUNCATE TABLE EDW_STAGING.ECDM_DIM_AGREEMENT_PRE_WORK;


CREATE LOCAL TEMPORARY TABLE ECDM_DIM_AGREEMENT_BENE_ID ON COMMIT PRESERVE ROWS AS
SELECT DISTINCT
    UUID_GEN(PREHASH_VALUE(
        CLEAN_STRING(SRC.CARR_ADMN_SYS_CD),
        CLEAN_STRING('IPA'),
        CLEAN_STRING(SRC.HLDG_KEY_PFX),
        CLEAN_STRING(SRC.AGRMNT_NUM),
        CLEAN_STRING(SRC.HLDG_KEY_SFX)))::UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID
FROM EDW_STAGING.ECDM_C_B_BENE_DSGN_OUT_SNAPSHOT SRC;


INSERT INTO ECDM_DIM_AGREEMENT_BENE_ID
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID
)
SELECT DIM_AGREEMENT_NATURAL_KEY_HASH_UUID
FROM EDW_TDSUNSET.REL_PARTY_AGREEMENT SRC
WHERE SRC.REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID = UUID_GEN(PREHASH_VALUE(CLEAN_STRING('BENE')))::UUID;


INSERT INTO EDW_STAGING.ECDM_DIM_AGREEMENT_PRE_WORK
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    AGREEMENT_NR_PFX,
    AGREEMENT_NR,
    AGREEMENT_NR_SFX,
    AGREEMENT_SOURCE_CDE,
    AGREEMENT_TYPE_CDE,
    AGREEMENT_STATUS_CDE,
    AGREEMENT_STATUS_REASON_CDE,
    BENEFICIARIES_RECORDED_IND,
    OPERATOR_IND,
    CHECK_SUM,
    BEGIN_DT,
    BEGIN_DTM,
    END_DT,
    END_DTM
)
SELECT
     UUID_GEN(PREHASH_VALUE(
        CLEAN_STRING(SRC.CARR_ADMN_SYS_CD),
        CLEAN_STRING('IPA'),
        CLEAN_STRING(SRC.HLDG_KEY_PFX),
        CLEAN_STRING(SRC.AGRMNT_NUM),
        CLEAN_STRING(SRC.HLDG_KEY_SFX)))::UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
     CLEAN_STRING(SRC.HLDG_KEY_PFX) AS AGREEMENT_NR_PFX,
     CLEAN_STRING(SRC.AGRMNT_NUM) AS AGREEMENT_NR,
     CLEAN_STRING(SRC.HLDG_KEY_SFX) AS AGREEMENT_NR_SFX,
     CLEAN_STRING(SRC.CARR_ADMN_SYS_CD) AS AGREEMENT_SOURCE_CDE,
     CLEAN_STRING('IPA') AS AGREEMENT_TYPE_CDE,
     CLEAN_STRING(SRC.OVERALL_STS) AS AGREEMENT_STATUS_CDE,
     CLEAN_STRING(SRC.STATUS_RSN) AS AGREEMENT_STATUS_REASON_CDE,
     CASE WHEN BENE.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID IS NULL THEN FALSE ELSE TRUE END AS BENEFICIARIES_RECORDED_IND,
     SRC.ADD_UPD_DEL_IND AS OPERATOR_IND,
     UUID_GEN(PREHASH_VALUE(
        CLEAN_STRING(SRC.OVERALL_STS),
        CLEAN_STRING(SRC.STATUS_RSN),
        CASE WHEN BENE.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID IS NULL THEN FALSE ELSE TRUE END
    ))::UUID AS CHECK_SUM,
    SRC.SRC_LST_MOD_TS::DATE AS BEGIN_DT,
    SRC.SRC_LST_MOD_TS::TIMESTAMP AS BEGIN_DTM,
    '9999-12-31' AS END_DT,
    '9999-12-31'::TIMESTAMP AS END_DTM

FROM EDW_STAGING.ECDM_C_B_AGRMNT_OUT SRC
LEFT JOIN ECDM_DIM_AGREEMENT_BENE_ID BENE ON
UUID_GEN(PREHASH_VALUE(
        CLEAN_STRING(SRC.CARR_ADMN_SYS_CD),
        CLEAN_STRING('IPA'),
        CLEAN_STRING(SRC.HLDG_KEY_PFX),
        CLEAN_STRING(SRC.AGRMNT_NUM),
        CLEAN_STRING(SRC.HLDG_KEY_SFX)))::UUID = BENE.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID;


-- Apply delete records
INSERT INTO EDW_WORK.ECDM_DIM_AGREEMENT
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    AGREEMENT_NR_PFX,
    AGREEMENT_NR,
    AGREEMENT_NR_SFX,
    AGREEMENT_SOURCE_CDE,
    AGREEMENT_TYPE_CDE,
    AGREEMENT_STATUS_CDE,
    AGREEMENT_STATUS_REASON_CDE,
    BENEFICIARIES_RECORDED_IND,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID
)
SELECT
    SRC.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    SRC.AGREEMENT_NR_PFX AS AGREEMENT_NR_PFX,
    SRC.AGREEMENT_NR AS AGREEMENT_NR,
    SRC.AGREEMENT_NR_SFX AS AGREEMENT_NR_SFX,
    SRC.AGREEMENT_SOURCE_CDE AS AGREEMENT_SOURCE_CDE,
    SRC.AGREEMENT_TYPE_CDE AS AGREEMENT_TYPE_CDE,
    SRC.AGREEMENT_STATUS_CDE AS AGREEMENT_STATUS_CDE,
    SRC.AGREEMENT_STATUS_REASON_CDE AS AGREEMENT_STATUS_REASON_CDE,
    SRC.BENEFICIARIES_RECORDED_IND AS BENEFICIARIES_RECORDED_IND,
    CASE WHEN TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID IS NOT NULL THEN TGT.BEGIN_DT ELSE '0001-01-01' END AS BEGIN_DT,
    CASE WHEN TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID IS NOT NULL THEN TGT.BEGIN_DTM ELSE '0001-01-01' END AS BEGIN_DTM,
    CURRENT_TIMESTAMP(6) AS ROW_PROCESS_DTM,
    CASE WHEN TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID IS NOT NULL THEN TGT.audit_id ELSE :audit_id END AS AUDIT_ID,
    FALSE AS LOGICAL_DELETE_IND,
    SRC.CHECK_SUM AS CHECK_SUM,
    FALSE AS CURRENT_ROW_IND,
    SRC.BEGIN_DT AS END_DT,
    SRC.BEGIN_DTM AS END_DTM,
    TGT.SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID,
    FALSE AS RESTRICTED_ROW_IND,
    :audit_id AS UPDATE_AUDIT_ID

FROM EDW_STAGING.ECDM_DIM_AGREEMENT_PRE_WORK SRC
LEFT JOIN EDW_TDSUNSET.DIM_AGREEMENT TGT
ON SRC.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID = TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID
AND TGT.CURRENT_ROW_IND = TRUE
AND TGT.SOURCE_SYSTEM_ID IN ('44', '45')
WHERE SRC.OPERATOR_IND = 'D';


-- Apply insert
INSERT INTO EDW_WORK.ECDM_DIM_AGREEMENT
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    AGREEMENT_NR_PFX,
    AGREEMENT_NR,
    AGREEMENT_NR_SFX,
    AGREEMENT_SOURCE_CDE,
    AGREEMENT_TYPE_CDE,
    AGREEMENT_STATUS_CDE,
    AGREEMENT_STATUS_REASON_CDE,
    BENEFICIARIES_RECORDED_IND,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID
)
SELECT
    SRC.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    SRC.AGREEMENT_NR_PFX AS AGREEMENT_NR_PFX,
    SRC.AGREEMENT_NR AS AGREEMENT_NR,
    SRC.AGREEMENT_NR_SFX AS AGREEMENT_NR_SFX,
    SRC.AGREEMENT_SOURCE_CDE AS AGREEMENT_SOURCE_CDE,
    SRC.AGREEMENT_TYPE_CDE AS AGREEMENT_TYPE_CDE,
    SRC.AGREEMENT_STATUS_CDE AS AGREEMENT_STATUS_CDE,
    SRC.AGREEMENT_STATUS_REASON_CDE AS AGREEMENT_STATUS_REASON_CDE,
    SRC.BENEFICIARIES_RECORDED_IND AS BENEFICIARIES_RECORDED_IND,
    '0001-01-01' AS BEGIN_DT,
    '0001-01-01' AS BEGIN_DTM,
    CURRENT_TIMESTAMP(6) AS ROW_PROCESS_DTM,
    CASE WHEN TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID IS NOT NULL THEN TGT.audit_id ELSE :audit_id END AS AUDIT_ID,
    FALSE AS LOGICAL_DELETE_IND,
    SRC.CHECK_SUM AS CHECK_SUM,
    TRUE AS CURRENT_ROW_IND,
    SRC.END_DT AS END_DT,
    SRC.END_DTM AS END_DTM,
    '45' AS SOURCE_SYSTEM_ID,
    FALSE AS RESTRICTED_ROW_IND,
    :audit_id AS UPDATE_AUDIT_ID

FROM EDW_STAGING.ECDM_DIM_AGREEMENT_PRE_WORK SRC
WHERE SRC.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID NOT IN
(SELECT DISTINCT DIM_AGREEMENT_NATURAL_KEY_HASH_UUID FROM EDW_TD_SUNSET.DIM_AGREEMENT WHERE LOGICAL_DELETE_IND = FALSE)
AND OPERATOR_IND != 'D';


-- Apply update current row
INSERT INTO EDW_WORK.ECDM_DIM_AGREEMENT
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    AGREEMENT_NR_PFX,
    AGREEMENT_NR,
    AGREEMENT_NR_SFX,
    AGREEMENT_SOURCE_CDE,
    AGREEMENT_TYPE_CDE,
    AGREEMENT_STATUS_CDE,
    AGREEMENT_STATUS_REASON_CDE,
    BENEFICIARIES_RECORDED_IND,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID
)
SELECT
    SRC.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    SRC.AGREEMENT_NR_PFX AS AGREEMENT_NR_PFX,
    SRC.AGREEMENT_NR AS AGREEMENT_NR,
    SRC.AGREEMENT_NR_SFX AS AGREEMENT_NR_SFX,
    SRC.AGREEMENT_SOURCE_CDE AS AGREEMENT_SOURCE_CDE,
    SRC.AGREEMENT_TYPE_CDE AS AGREEMENT_TYPE_CDE,
    SRC.AGREEMENT_STATUS_CDE AS AGREEMENT_STATUS_CDE,
    SRC.AGREEMENT_STATUS_REASON_CDE AS AGREEMENT_STATUS_REASON_CDE,
    SRC.BENEFICIARIES_RECORDED_IND AS BENEFICIARIES_RECORDED_IND,
    SRC.BEGIN_DT AS BEGIN_DT,
    SRC.BEGIN_DTM AS BEGIN_DTM,
    CURRENT_TIMESTAMP(6) AS ROW_PROCESS_DTM,
    TGT.audit_id AS AUDIT_ID,
    FALSE AS LOGICAL_DELETE_IND,
    SRC.CHECK_SUM AS CHECK_SUM,
    TRUE AS CURRENT_ROW_IND,
    SRC.END_DT AS END_DT,
    SRC.END_DTM AS END_DTM,
    '45' AS SOURCE_SYSTEM_ID,
    FALSE AS RESTRICTED_ROW_IND,
    :audit_id AS UPDATE_AUDIT_ID

FROM EDW_STAGING.ECDM_DIM_AGREEMENT_PRE_WORK SRC
WHERE SRC.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID IN
(SELECT DISTINCT DIM_AGREEMENT_NATURAL_KEY_HASH_UUID FROM EDW_TD_SUNSET.DIM_AGREEMENT WHERE CURRENT_ROW_IND = TRUE AND
SOURCE_SYSTEM_ID IN ('45', '44'))
AND OPERATOR_IND != 'D';


-- Apply update historical record
INSERT INTO EDW_WORK.ECDM_DIM_AGREEMENT
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    AGREEMENT_NR_PFX,
    AGREEMENT_NR,
    AGREEMENT_NR_SFX,
    AGREEMENT_SOURCE_CDE,
    AGREEMENT_TYPE_CDE,
    AGREEMENT_STATUS_CDE,
    AGREEMENT_STATUS_REASON_CDE,
    BENEFICIARIES_RECORDED_IND,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID
)
SELECT
    TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    TGT.AGREEMENT_NR_PFX AS AGREEMENT_NR_PFX,
    TGT.AGREEMENT_NR AS AGREEMENT_NR,
    TGT.AGREEMENT_NR_SFX AS AGREEMENT_NR_SFX,
    TGT.AGREEMENT_SOURCE_CDE AS AGREEMENT_SOURCE_CDE,
    TGT.AGREEMENT_TYPE_CDE AS AGREEMENT_TYPE_CDE,
    TGT.AGREEMENT_STATUS_CDE AS AGREEMENT_STATUS_CDE,
    TGT.AGREEMENT_STATUS_REASON_CDE AS AGREEMENT_STATUS_REASON_CDE,
    TGT.BENEFICIARIES_RECORDED_IND AS BENEFICIARIES_RECORDED_IND,
    TGT.BEGIN_DT AS BEGIN_DT,
    TGT.BEGIN_DTM AS BEGIN_DTM,
    TGT.ROW_PROCESS_DTM AS ROW_PROCESS_DTM,
    TGT.AUDIT_ID AS AUDIT_ID,
    TGT.LOGICAL_DELETE_IND AS LOGICAL_DELETE_IND,
    TGT.CHECK_SUM AS CHECK_SUM,
    FALSE AS CURRENT_ROW_IND,
    SRC.BEGIN_DT - INTERVAL '1 day' AS END_DT,
    SRC.BEGIN_DTM - INTERVAL '1 sec' AS END_DTM,
    TGT.SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID,
    TGT.RESTRICTED_ROW_IND AS RESTRICTED_ROW_IND,
    :audit_id AS UPDATE_AUDIT_ID

FROM EDW_STAGING.ECDM_DIM_AGREEMENT_PRE_WORK SRC
LEFT JOIN EDW_TDSUNSET.DIM_AGREEMENT TGT
ON SRC.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID = TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID
AND TGT.CURRENT_ROW_IND = TRUE
WHERE OPERATOR_IND != 'D' AND TGT.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID IS NOT NULL
AND TGT.SOURCE_SYSTEM_IND IN ('44', '45');
