TRUNCATE TABLE EDW_WORK.ECDM_DIM_ADDRESS;


INSERT INTO EDW_WORK.ECDM_DIM_ADDRESS
(
    DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    ATTENTION_LINE_TXT,
    ADDRESS_STREET_1_TXT,
    ADDRESS_STREET_2_TXT,
    ADDRESS_STREET_3_TXT,
    ADDRESS_STREET_4_TXT,
    CITY_NM,
    STATE_CDE,
    ZIP_CDE,
    ZIP_6_9_CDE,
    ZIP_10_13_CDE,
    COUNTRY_CDE,
    ADDRESS_VALIDATION_CDE,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    FOREIGN_POSTAL_CDE,
    FULL_POSTAL_CDE,
    ADDRESS_VERIFIED_DT,
    SOURCE_SYSTEM_ADDRESS_ID
)
SELECT
    UUID_GEN(PREHASH_VALUE(
        CLEAN_STRING(SRC.AD_L1_TXT),
        CLEAN_STRING(SRC.AD_L2_TXT),
        CLEAN_STRING(SRC.AD_L3_TXT),
        CLEAN_STRING(SRC.AD_L4_TXT),
        CLEAN_STRING(SRC.CITY),
        CLEAN_STRING(SRC.STATE),
        CLEAN_STRING(SRC.ZIP_1_5_NR),
        CLEAN_STRING(SRC.ZIP_6_9_NR),
        CLEAN_STRING(SRC.ZIP_10_13_NR),
        CLEAN_STRING(SRC.CTRY_CD)))::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    NULL AS ATTENTION_LINE_TXT,
    CLEAN_STRING(SRC.AD_L1_TXT) AS ADDRESS_STREET_1_TXT,
    CLEAN_STRING(SRC.AD_L2_TXT) AS ADDRESS_STREET_2_TXT,
    CLEAN_STRING(SRC.AD_L3_TXT) AS ADDRESS_STREET_3_TXT,
    CLEAN_STRING(SRC.AD_L4_TXT) AS ADDRESS_STREET_4_TXT,
    CLEAN_STRING(SRC.CITY) AS CITY_NM,
    CLEAN_STRING(SRC.STATE) AS STATE_CDE,
    CLEAN_STRING(SRC.ZIP_1_5_NR) AS ZIP_CDE,
    CLEAN_STRING(SRC.ZIP_6_9_NR) AS ZIP_6_9_CDE,
    CLEAN_STRING(SRC.ZIP_10_13_NR) AS ZIP_10_13_CDE,
    CLEAN_STRING(SRC.CTRY_CD) AS COUNTRY_CDE,
    CLEAN_STRING(SRC.ADDR_VAL_CD) AS ADDRESS_VALIDATION_CDE,
    '0001-01-01' AS BEGIN_DT,
    '0001-01-01 00:00:00' AS BEGIN_DTM,
    CURRENT_TIMESTAMP(6) AS ROW_PROCESS_DTM,
    0 AS AUDIT_ID,
    FALSE AS LOGICAL_DELETE_IND,
    UUID_GEN(PREHASH_VALUE(
        CLEAN_STRING(SRC.ADDR_VAL_CD),
        CASE WHEN CLEAN_STRING(SRC.DMST_FRGN_CD) = CLEAN_STRING('FOR') THEN CLEAN_STRING(SRC.ZIP_1_5_NR) END,
        SRC.ADDR_VER_DT
    ))::UUID AS CHECK_SUM,
    TRUE AS CURRENT_ROW_IND,
    '9999-12-31' AS END_DT,
    '9999-12-31'::TIMESTAMP  AS END_DTM,
    SRC.SRC_SYS_ID AS SOURCE_SYSTEM_ID,
    FALSE AS RESTRICTED_ROW_IND,
    0 AS UPDATE_AUDIT_ID,
    CASE WHEN CLEAN_STRING(SRC.DMST_FRGN_CD) = CLEAN_STRING('FOR') THEN CLEAN_STRING(SRC.ZIP_1_5_NR) END AS FOREIGN_POSTAL_CDE,
    CLEAN_STRING(SRC.FULL_POST_CD) AS FULL_POSTAL_CDE,
    SRC.ADDR_VER_DT AS ADDRESS_VERIFIED_DT,
    CLEAN_STRING(SRC.SRC_SYS_AD_ID) AS SOURCE_SYSTEM_ADDRESS_ID

FROM
-- Add dedup logic here
(
SELECT
    *,
    ROW_NUMBER() OVER (PARTITION BY
        CLEAN_STRING(SRC_DUP.AD_L1_TXT),
        CLEAN_STRING(SRC_DUP.AD_L2_TXT),
        CLEAN_STRING(SRC_DUP.AD_L3_TXT),
        CLEAN_STRING(SRC_DUP.AD_L4_TXT),
        CLEAN_STRING(SRC_DUP.CITY),
        CLEAN_STRING(SRC_DUP.STATE),
        CLEAN_STRING(SRC_DUP.ZIP_1_5_NR),
        CLEAN_STRING(SRC_DUP.ZIP_6_9_NR),
        CLEAN_STRING(SRC_DUP.ZIP_10_13_NR),
        CLEAN_STRING(SRC_DUP.CTRY_CD) ORDER BY SRC_DUP.ADDR_VER_DT, SRC_DUP.SRC_SYS_AD_ID DESC) AS RNK
    FROM PROD_STND_PRTY_VW_TERSUN.ST_AD_VW SRC_DUP
) SRC
WHERE SRC.RNK = 1;
-- For initial load we will not use Tier2 merge logic, we can keep this process idempotent


DELETE FROM EDW_TDSUNSET.DIM_ADDRESS WHERE SOURCE_SYSTEM_ID IN ('44', '45');


INSERT INTO EDW_TDSUNSET.DIM_ADDRESS
(
    DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    ATTENTION_LINE_TXT,
    ADDRESS_STREET_1_TXT,
    ADDRESS_STREET_2_TXT,
    ADDRESS_STREET_3_TXT,
    ADDRESS_STREET_4_TXT,
    CITY_NM,
    STATE_CDE,
    ZIP_CDE,
    ZIP_6_9_CDE,
    ZIP_10_13_CDE,
    COUNTRY_CDE,
    ADDRESS_VALIDATION_CDE,
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    FOREIGN_POSTAL_CDE,
    FULL_POSTAL_CDE,
    ADDRESS_VERIFIED_DT,
    SOURCE_SYSTEM_ADDRESS_ID
)
SELECT
    SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID,
    SRC.ATTENTION_LINE_TXT,
    SRC.ADDRESS_STREET_1_TXT,
    SRC.ADDRESS_STREET_2_TXT,
    SRC.ADDRESS_STREET_3_TXT,
    SRC.ADDRESS_STREET_4_TXT,
    SRC.CITY_NM,
    SRC.STATE_CDE,
    SRC.ZIP_CDE,
    SRC.ZIP_6_9_CDE,
    SRC.ZIP_10_13_CDE,
    SRC.COUNTRY_CDE,
    SRC.ADDRESS_VALIDATION_CDE,
    SRC.BEGIN_DT,
    SRC.BEGIN_DTM,
    SRC.ROW_PROCESS_DTM,
    SRC.AUDIT_ID,
    SRC.LOGICAL_DELETE_IND,
    SRC.CHECK_SUM,
    SRC.CURRENT_ROW_IND,
    SRC.END_DT,
    SRC.END_DTM,
    SRC.SOURCE_SYSTEM_ID,
    SRC.RESTRICTED_ROW_IND,
    SRC.UPDATE_AUDIT_ID,
    SRC.FOREIGN_POSTAL_CDE,
    SRC.FULL_POSTAL_CDE,
    SRC.ADDRESS_VERIFIED_DT,
    SRC.SOURCE_SYSTEM_ADDRESS_ID

FROM EDW_WORK.ECDM_DIM_ADDRESS SRC;
